title = "NIME Future Leaders Workshop"
institution = "New Interfaces for Musical Expression"
author = "Charles Patrick Martin, Stefano Fasciani, Juan Martinez Avila, Fabio Morreale, Andrew McPherson, Courtney N. Reed, Pia van Gelder, Yichen Wang, Doga Cavdir"
year = "2026"
